---
driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: ubuntu-jammy
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
    privileged: true

  - name: ubuntu-focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    USER: 'valet-sh'
    GROUP: 'valet-sh'

verifier:
  name: testinfra
  options:
    'v': true
    's': true

scenario:
  name: default
  test_sequence:
    - lint
    - syntax
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
